package com.RestProject1.springrestapi.dto;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "All attributes of Benifits")
public class BenifitsDTO {
	
	@ApiModelProperty(notes = "AutoGenerated ID")
	private Long id;
	
	@NotNull
	@NotBlank
	@ApiModelProperty(notes = "can be STANDARD, ADVANCED OR PREMIUM", required = true)
	private String retirementPlan;
	
	@NotNull
	@NotBlank
	@ApiModelProperty(notes = "can be STANDARD, ADVANCED OR PREMIUM", required = true)
	private String laptop;
	
	@NotNull
	@NotBlank
	@ApiModelProperty(notes = "can be STANDARD, ADVANCED OR PREMIUM", required = true)
	private String healthcare;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getRetirementPlan() {
		return retirementPlan;
	}
	public void setRetirementPlan(String retirementPlan) {
		this.retirementPlan = retirementPlan;
	}
	public String getLaptop() {
		return laptop;
	}
	public void setLaptop(String laptop) {
		this.laptop = laptop;
	}
	public String getHealthcare() {
		return healthcare;
	}
	public void setHealthcare(String healthcare) {
		this.healthcare = healthcare;
	}
	@Override
	public String toString() {
		return "BenifitsDTO [id=" + id + ", retirementPlan=" + retirementPlan + ", laptop=" + laptop + ", healthcare="
				+ healthcare + "]";
	}
	public BenifitsDTO(Long id, String retirementPlan, String laptop, String healthcare) {
		super();
		this.id = id;
		this.retirementPlan = retirementPlan;
		this.laptop = laptop;
		this.healthcare = healthcare;
	}
	public BenifitsDTO() {
		super();
		// TODO Auto-generated constructor stub
	}

	
	
}
