package com.RestProject1.springrestapi.dto;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Length;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "All attributes of Department")
public class DepartmentDTO {
	
	@ApiModelProperty(notes = "AutoGenerated ID")
	private Long id;
	
	
	@NotNull
	@NotBlank
	@Length(min=2, message ="Name should be of atleast two alphabets ")
	@ApiModelProperty(notes = "Name should be of atleast two alphabets", required = true)
	private String name;
	
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Override
	public String toString() {
		return "DepartmentDTO [id=" + id + ", name=" + name + "]";
	}
	public DepartmentDTO(Long id, String name) {
		super();
		this.id = id;
		this.name = name;
	}
	public DepartmentDTO() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	

}
